################################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: delegation-token-test
spec:
  image: gaborgsomogyi/flink:latest
  flinkVersion: v1_16
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    kubernetes.container.image.pull-policy: Never
    state.savepoints.dir: file:///flink-data/savepoints
    state.checkpoints.dir: file:///flink-data/checkpoints
    execution.checkpointing.interval: "1m"
    security.delegation.tokens.renewal.retry.backoff: 1min

# Kerberos delegation token test
#    kubernetes.decorator.hadoop-conf-mount.enabled: "false"
#    kubernetes.decorator.kerberos-mount.enabled: "false"
#    env.java.opts: "-Dsun.security.krb5.debug=true"
#    env.hadoop.conf.dir: /share
#    flink.hadoop.hadoop.security.authentication: kerberos
#    security.kerberos.access.hadoopFileSystems: hdfs://hdfs:9000
#    security.kerberos.login.keytab: /share/user.keytab
#    security.kerberos.login.principal: user
#    security.kerberos.krb5-conf.path: /share/krb5.conf

# S3 delegation token test
    security.delegation.token.provider.s3.region: REPLACE_ME
    security.delegation.token.provider.s3.access-key: REPLACE_ME
    security.delegation.token.provider.s3.secret-key: REPLACE_ME
  serviceAccount: flink
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-template
    spec:
      containers:
        # Do not change the main container name
        - name: flink-main-container
          volumeMounts:
            - mountPath: /share
              name: share
            - mountPath: /flink-data
              name: flink-volume
# Long live S3 credentials test
#          env:
#            - name: AWS_REGION
#              value: REPLACE_ME
#            - name: AWS_ACCESS_KEY_ID
#              value: REPLACE_ME
#            - name: AWS_SECRET_ACCESS_KEY
#              value: REPLACE_ME
      volumes:
        - name: share
          hostPath:
            path: /share
        - name: flink-volume
          hostPath:
            # directory location on host
            path: /tmp/flink
            # this field is optional
            type: Directory
  jobManager:
    resource:
      memory: "1024m"
      cpu: 1
  taskManager:
    resource:
      memory: "1024m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/examples/flink-test-java-job-1.0.jar
    entryClass: com.example.job.FlinkTestJavaJob
#    args: ["--sink", "file", "--sink-url", "hdfs://hdfs:9000/output"]
    args: ["--sink", "file", "--sink-url", "s3://REPLACE_ME/output"]
    parallelism: 2
  logConfiguration:
    "log4j-console.properties": |
      rootLogger.level = DEBUG
      rootLogger.appenderRef.file.ref = LogFile
      rootLogger.appenderRef.console.ref = LogConsole
      appender.file.name = LogFile
      appender.file.type = File
      appender.file.append = false
      appender.file.fileName = ${sys:log.file}
      appender.file.layout.type = PatternLayout
      appender.file.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%t] %-60c %x - %m%n
      appender.console.name = LogConsole
      appender.console.type = CONSOLE
      appender.console.layout.type = PatternLayout
      appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%t] %-60c %x - %m%n
      logger.akka.name = akka
      logger.akka.level = INFO
      logger.kafka.name= org.apache.kafka
      logger.kafka.level = INFO
      logger.hadoop.name = org.apache.hadoop
      logger.hadoop.level = DEBUG
      logger.zookeeper.name = org.apache.zookeeper
      logger.zookeeper.level = INFO
      logger.netty.name = org.apache.flink.shaded.akka.org.jboss.netty.channel.DefaultChannelPipeline
      logger.netty.level = OFF
